version: '3.3'
services:
  graphhopper:
    image: graphhopper
    container_name: graphhopper
    ports:
      - "8989:8989"
      - "8990:8990"
    volumes:
      - ./data:/data
      - ./data/logs:/graphhopper/logs
      - ./config-example.yml:/graphhopper/config-example.yml
      - ./graphhopper.sh:/graphhopper/graphhopper.sh
    entrypoint: /bin/bash
    command: ["./graphhopper.sh"]
