version: "3.9"
services:
  osm2pgsl:
    image: iboates/osm2pgsql:latest
    container_name: osm2pgsl
    ports:
      - "9090:8080"
    volumes:
      - /srv/osm2pgsql:/data
    restart: unless-stopped
