version: '3'
services:
  geoserver:
    container_name: geoserver
    build:
      context: .
      args:
        - GEOSERVER_VERSION=2.25.3
        - CORS_ENABLED=true
        - CORS_ALLOWED_METHODS=GET
    restart: always  
    ports:
      - "8090:8080"
    network_mode: "bridge"
    environment:
      - INSTALL_EXTENSIONS=true
      - STABLE_EXTENSIONS=oracle,vectortiles
      - EXTRA_JAVA_OPTS=-Xms1G -Xmx2G
      - CORS_ENABLED=true
    volumes:
      - /srv/geoserver/geoserver_data:/opt/geoserver_data/:Z
      - /srv/geoserver/additional_libs:/opt/additional_libs:Z # by mounting this we can install libs from host on startup
      - /srv/geoserver/tomcat/conf:/opt/apache-tomcat-9.0.89/conf:Z # by mounting this we can install libs from host on startup
    healthcheck:
      test: curl --fail "http://localhost:8080/geoserver/web/wicket/resource/org.geoserver.web.GeoServerBasePage/img/logo.png" || exit 1
      interval: 1m
      retries: 3
      timeout: 20s


