services:
  tileserver:
    image: mirror-docker.runflare.com/maptiler/tileserver-gl:latest
    container_name: tileserver
    ports:
      - "900:8080"
    volumes:
      - .:/data
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "4.0"
          memory: 5G
    networks:
      - map_services_net

networks:
  map_services_net:
    driver: bridge
